SICKLE_OPTS = 
SICKLE_PE_OPTS = 

%.pesickle.fastq: %_1.fastq.gz %_2.fastq.gz
	sickle pe $(SICKLE_OPTS) $(SICKLE_PE_OPTS) -f $< -r $(word 2,$^) -t sanger -o $(basename $@).r1.fastq -p $(basename $@).r2.fastq -s $(basename $@).stons.fastq
